# Generated by Django 2.1.5 on 2019-07-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GradeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '专业班级',
                'verbose_name_plural': '专业班级',
                'db_table': 'gradeclass',
            },
        ),
    ]
