# Generated by Django 2.1.5 on 2019-02-03 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('point', models.IntegerField()),
                ('right_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Multiple_Choice_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('option_A', models.CharField(max_length=1000)),
                ('option_B', models.CharField(max_length=1000)),
                ('option_C', models.CharField(max_length=1000)),
                ('option_D', models.CharField(max_length=1000)),
                ('point', models.IntegerField()),
                ('right_answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('multiple_choice_question_count', models.IntegerField()),
                ('multiple_choice_question_total_score', models.IntegerField()),
                ('essay_question_count', models.IntegerField()),
                ('essay_question_total_score', models.IntegerField()),
                ('make_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='multiple_choice_question',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examination.Paper'),
        ),
        migrations.AddField(
            model_name='essay_question',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examination.Paper'),
        ),
    ]
