# Generated by Django 2.1.5 on 2019-07-07 02:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('right_answer', models.TextField()),
                ('point', models.FloatField()),
            ],
            options={
                'verbose_name': '问答题',
                'verbose_name_plural': '问答题',
                'db_table': 'essay_question',
            },
        ),
        migrations.CreateModel(
            name='Multiple_Choice_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('option_A', models.CharField(max_length=1000)),
                ('option_B', models.CharField(max_length=1000)),
                ('option_C', models.CharField(max_length=1000)),
                ('option_D', models.CharField(max_length=1000)),
                ('point', models.FloatField()),
                ('right_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=None, max_length=1)),
            ],
            options={
                'verbose_name': '选择题',
                'verbose_name_plural': '选择题',
                'db_table': 'multiple_choice_question',
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.TextField()),
                ('multiple_choice_question_total_score', models.FloatField(default=0)),
                ('essay_question_total_score', models.FloatField(default=0)),
                ('publish_date', models.DateField(auto_now=True)),
                ('expire_date', models.DateField(default=datetime.date(2019, 8, 6))),
                ('is_published', models.BooleanField(default=False)),
                ('paper_maker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.Teacher')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'db_table': 'paper',
            },
        ),
        migrations.AddField(
            model_name='multiple_choice_question',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Examination.Paper'),
        ),
        migrations.AddField(
            model_name='essay_question',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Examination.Paper'),
        ),
    ]
