# Generated by Django 2.1.5 on 2019-02-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
