# Generated by Django 2.1.5 on 2019-06-06 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_question',
            name='point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='multiple_choice_question',
            name='point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='paper',
            name='essay_question_total_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='expire_date',
            field=models.DateField(default=datetime.date(2019, 7, 6)),
        ),
        migrations.AlterField(
            model_name='paper',
            name='multiple_choice_question_total_score',
            field=models.FloatField(default=0),
        ),
    ]
