# Generated by Django 2.1.5 on 2019-04-05 06:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay_question',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Examination.Paper'),
        ),
        migrations.AlterField(
            model_name='multiple_choice_question',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Examination.Paper'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='expire_date',
            field=models.DateField(default=datetime.date(2019, 5, 5)),
        ),
    ]
