# Generated by Django 2.1.5 on 2019-02-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0002_paper_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='make_time',
            field=models.DateField(auto_now=True),
        ),
    ]
