# Generated by Django 2.1.5 on 2019-06-07 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0002_auto_20190606_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='expire_date',
            field=models.DateField(default=datetime.date(2019, 7, 7)),
        ),
    ]
