# Generated by Django 2.1.5 on 2019-04-05 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0002_auto_20190405_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='essay_question_count',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='multiple_choice_question_count',
        ),
    ]
