# Generated by Django 2.1.5 on 2019-02-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0003_auto_20190203_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiple_choice_question',
            name='right_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='paper',
            name='essay_question_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='essay_question_total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='multiple_choice_question_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='paper',
            name='multiple_choice_question_total_score',
            field=models.IntegerField(default=0),
        ),
    ]
