# Generated by Django 2.1.5 on 2019-02-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0004_auto_20190206_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='make_time',
            new_name='publish_time',
        ),
    ]
