# Generated by Django 2.1.5 on 2019-02-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0005_auto_20190206_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='publish_time',
            new_name='publish_date',
        ),
    ]
