# Generated by Django 2.1.5 on 2019-02-08 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
        ('Examination', '0006_auto_20190206_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='paper_maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Teacher.Teacher'),
        ),
    ]
