# Generated by Django 2.1.5 on 2019-03-18 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0007_paper_paper_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='expire_date',
            field=models.DateField(default=datetime.date(2019, 4, 17)),
        ),
    ]
