# Generated by Django 2.1.5 on 2019-03-24 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0008_paper_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='expire_date',
            field=models.DateField(default=datetime.date(2019, 4, 23)),
        ),
    ]
