# Generated by Django 2.1.5 on 2019-08-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user_type', models.CharField(max_length=50)),
                ('access_date', models.DateField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': '访问记录',
                'verbose_name_plural': '访问记录',
                'db_table': 'history_record',
            },
        ),
    ]
