# Generated by Django 2.1.5 on 2019-04-01 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GradeClass', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Examination', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField()),
                ('essay_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examination.Essay_Question')),
            ],
        ),
        migrations.CreateModel(
            name='EssayComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('score', models.IntegerField()),
                ('essay_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.EssayAnswer')),
            ],
        ),
        migrations.CreateModel(
            name='PaperAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_count', models.IntegerField(default=0)),
                ('paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examination.Paper')),
            ],
        ),
        migrations.CreateModel(
            name='PaperResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_question_result', models.IntegerField(default=0)),
                ('essay_question_result', models.IntegerField(default=0)),
                ('does_choice_question_submit', models.BooleanField(default=False)),
                ('does_essay_question_submit', models.BooleanField(default=False)),
                ('submit_date', models.DateField(auto_now=True)),
                ('paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examination.Paper')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('grade_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradeClass.GradeClass')),
                ('paper_result', models.ManyToManyField(through='Student.PaperResult', to='Examination.Paper')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paperresult',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.Student'),
        ),
        migrations.AddField(
            model_name='paperanswer',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.Student'),
        ),
        migrations.AddField(
            model_name='essaycomment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.Student'),
        ),
        migrations.AddField(
            model_name='essayanswer',
            name='paper_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.PaperAnswer'),
        ),
    ]
