# Generated by Django 2.1.5 on 2019-04-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essaycomment',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='essaycomment',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
