# Generated by Django 2.1.5 on 2019-02-24 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0007_paper_paper_maker'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_question_result', models.IntegerField()),
                ('essay_question_result', models.IntegerField()),
                ('submit_date', models.DateField()),
                ('paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examination.Paper')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='paper_result',
            field=models.ManyToManyField(through='Student.PaperResult', to='Examination.Paper'),
        ),
    ]
