# Generated by Django 2.1.5 on 2019-02-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20190224_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperresult',
            name='does_choice_question_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paperresult',
            name='does_essay_question_submit',
            field=models.BooleanField(default=False),
        ),
    ]
