# Generated by Django 2.1.5 on 2019-03-14 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Examination', '0007_paper_paper_maker'),
        ('Student', '0005_auto_20190228_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField()),
                ('comment_count', models.IntegerField()),
                ('comment_1', models.TextField()),
                ('comment_2', models.TextField()),
                ('comment_3', models.TextField()),
                ('comment_4', models.TextField()),
                ('comment_5', models.TextField()),
                ('score_1', models.IntegerField()),
                ('score_2', models.IntegerField()),
                ('score_3', models.IntegerField()),
                ('score_4', models.IntegerField()),
                ('score_5', models.IntegerField()),
                ('essay_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Examination.Essay_Question')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.Student')),
            ],
        ),
    ]
