# Generated by Django 2.1.5 on 2019-03-15 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_essayanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='essayanswer',
            name='comment_1',
        ),
        migrations.RemoveField(
            model_name='essayanswer',
            name='comment_2',
        ),
        migrations.RemoveField(
            model_name='essayanswer',
            name='comment_3',
        ),
        migrations.RemoveField(
            model_name='essayanswer',
            name='comment_4',
        ),
        migrations.RemoveField(
            model_name='essayanswer',
            name='comment_5',
        ),
        migrations.RemoveField(
            model_name='essayanswer',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='essayanswer',
            name='score_1',
        ),
        migrations.RemoveField(
            model_name='essayanswer',
            name='score_2',
        ),
        migrations.RemoveField(
            model_name='essayanswer',
            name='score_3',
        ),
        migrations.RemoveField(
            model_name='essayanswer',
            name='score_4',
        ),
        migrations.RemoveField(
            model_name='essayanswer',
            name='score_5',
        ),
        migrations.AddField(
            model_name='essaycomment',
            name='essay_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Student.EssayAnswer'),
        ),
    ]
