# Generated by Django 2.1.5 on 2019-03-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GradeClass', '0001_initial'),
        ('Student', '0007_auto_20190315_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GradeClass.GradeClass'),
        ),
    ]
