# Generated by Django 2.1.5 on 2019-03-24 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_student_grade_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='grade_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GradeClass.GradeClass'),
        ),
    ]
