# Generated by Django 2.1.5 on 2019-03-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='upload_date',
            field=models.DateField(auto_now=True),
        ),
    ]
